name: persist_nav_bar_tab_bar
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.4
  persistent_bottom_nav_bar_v2: ^4.2.8
  riverpod_annotation: ^2.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.1.6
  riverpod_lint: ^1.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
